spring.application.name=compat-foundry-example
spring.jmx.enabled=true
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.redis.database=4
management.metrics.export.prometheus.enabled=false
management.health.redis.enabled=false
